import type { SmartSearchIntent } from '@dagestan/shared';

/**
 * Настоящие ответы Qwen3 8B (Ollama, temperature 0) на фразы мобильного
 * поиска — сняты 2026-10-04 с живого API через след ответа (requestId).
 * Тесты подставляют их вместо модели: так проверяется путь «ответ модели →
 * сервер → ответ приложению → фильтры экрана» на том, что модель реально
 * возвращает, а не на придуманных намерениях.
 *
 * Ключ — фраза человека; уточнения («до миллиона») сняты в той же сессии,
 * что и начало разговора, — с прошлым контекстом в подсказке.
 */
export const REAL_MOBILE: Readonly<Record<string, SmartSearchIntent>> = {
  'Хочу тойота суксид': {
    schemaVersion: '1',
    intent: 'search',
    domain: 'listings',
    query: null,
    filters: {
      category: 'transport-cars',
      brand: 'Toyota',
      model: 'Succeed',
    },
    preferences: {},
    location: null,
    time: null,
    sort: null,
    clarification: {
      needed: false,
      question: null,
      options: [],
    },
    confidence: 0.9,
    unresolved: [],
    subqueries: [],
  },
  'Хочу тойота суксид до 1.2 млн автомат бензин': {
    schemaVersion: '1',
    intent: 'search',
    domain: 'listings',
    query: null,
    filters: {
      category: 'transport-cars',
      brand: 'Toyota',
      model: 'Succeed',
      price: {
        max: 1200000,
      },
      gearbox: 'автомат',
      fuel: 'бензин',
    },
    preferences: {},
    location: null,
    time: null,
    sort: null,
    clarification: {
      needed: false,
      question: null,
      options: [],
    },
    confidence: 0.95,
    unresolved: [],
    subqueries: [],
  },
  'нужен суксид на автомате до миллиона': {
    schemaVersion: '1',
    intent: 'search',
    domain: 'listings',
    query: null,
    filters: {
      category: 'transport-cars',
      brand: 'Suksid',
      gearbox: 'автомат',
      price: {
        max: 1000000,
      },
    },
    preferences: {},
    location: null,
    time: null,
    sort: null,
    clarification: {
      needed: false,
      question: null,
      options: [],
    },
    confidence: 0.9,
    unresolved: [],
    subqueries: [],
  },
  'Что сегодня посмотреть в кино в Махачкале?': {
    schemaVersion: '1',
    intent: 'search',
    domain: 'cinema',
    query: null,
    filters: {
      movie: 'смотреть',
    },
    preferences: {},
    location: {
      city: 'Махачкала',
      nearMe: false,
      preferred: false,
    },
    time: {
      date: 'today',
      from: null,
      to: null,
      period: null,
    },
    sort: null,
    clarification: {
      needed: false,
      question: null,
      options: [],
    },
    confidence: 0.9,
    unresolved: [],
    subqueries: [],
  },
  'Что сегодня нового в Дагестане?': {
    schemaVersion: '1',
    intent: 'search',
    domain: 'news',
    query: null,
    filters: {
      scope: 'dagestan',
    },
    preferences: {},
    location: {
      city: null,
      nearMe: false,
      preferred: false,
    },
    time: {
      date: 'today',
      from: null,
      to: null,
      period: null,
    },
    sort: null,
    clarification: {
      needed: false,
      question: null,
      options: [],
    },
    confidence: 0.9,
    unresolved: [],
    subqueries: [],
  },
  'Хочу заказать пиццу в Каспийске': {
    schemaVersion: '1',
    intent: 'action',
    domain: 'delivery',
    query: null,
    filters: {
      dish: 'пицца',
    },
    preferences: {},
    location: {
      city: 'Каспийск',
      nearMe: false,
      preferred: false,
    },
    time: {
      date: null,
      from: null,
      to: null,
      period: null,
    },
    sort: null,
    clarification: {
      needed: false,
      question: null,
      options: [],
    },
    confidence: 0.9,
    unresolved: [],
    subqueries: [],
  },
  'Где поесть хинкал в Каспийске?': {
    schemaVersion: '1',
    intent: 'search',
    domain: 'delivery',
    query: 'хинкал',
    filters: {
      dish: 'хинкал',
      city: 'Каспийск',
    },
    preferences: {},
    location: {
      city: 'Каспийск',
      nearMe: false,
      preferred: false,
    },
    time: {
      date: null,
      from: null,
      to: null,
      period: null,
    },
    sort: null,
    clarification: {
      needed: false,
      question: null,
      options: [],
    },
    confidence: 0.9,
    unresolved: [],
    subqueries: [],
  },
  'Нужна доставка пиццы в Каспийске': {
    schemaVersion: '1',
    intent: 'search',
    domain: 'delivery',
    query: null,
    filters: {
      dish: 'пицца',
    },
    preferences: {},
    location: {
      city: 'Каспийск',
      nearMe: false,
      preferred: false,
    },
    time: {
      date: null,
      from: null,
      to: null,
      period: null,
    },
    sort: null,
    clarification: {
      needed: false,
      question: null,
      options: [],
    },
    confidence: 0.9,
    unresolved: [],
    subqueries: [],
  },
  'Хочу квартиру посуточно в Махачкале': {
    schemaVersion: '1',
    intent: 'search',
    domain: 'listings',
    query: null,
    filters: {
      category: 'realty-flats',
      transactionType: 'rent',
      rentPeriod: 'daily',
    },
    preferences: {},
    location: {
      city: 'Махачкала',
      nearMe: false,
      preferred: false,
    },
    time: {
      date: 'today',
      from: null,
      to: null,
      period: null,
    },
    sort: null,
    clarification: {
      needed: false,
      question: null,
      options: [],
    },
    confidence: 0.9,
    unresolved: [],
    subqueries: [],
  },
  'Какая сегодня погода в Дербенте?': {
    schemaVersion: '1',
    intent: 'search',
    domain: 'news',
    query: null,
    filters: {
      topic: 'погода',
    },
    preferences: {},
    location: {
      city: 'Дербент',
      nearMe: false,
      preferred: false,
    },
    time: {
      date: 'today',
      from: null,
      to: null,
      period: null,
    },
    sort: null,
    clarification: {
      needed: false,
      question: null,
      options: [],
    },
    confidence: 0.9,
    unresolved: [],
    subqueries: [],
  },
  'Хочу машину': {
    schemaVersion: '1',
    intent: 'search',
    domain: 'listings',
    query: null,
    filters: {
      category: 'transport-cars',
    },
    preferences: {},
    location: null,
    time: null,
    sort: null,
    clarification: {
      needed: true,
      question: 'Какой тип машины искать?',
      options: [],
    },
    confidence: 0.3,
    unresolved: ['машину'],
    subqueries: [],
  },
  Toyota: {
    schemaVersion: '1',
    intent: 'refine',
    domain: 'listings',
    query: null,
    filters: {
      brand: 'Toyota',
    },
    preferences: {},
    location: null,
    time: null,
    sort: null,
    clarification: {
      needed: false,
      question: null,
      options: [],
    },
    confidence: 0.9,
    unresolved: [],
    subqueries: [],
  },
  'Хочу квартиру': {
    schemaVersion: '1',
    intent: 'search',
    domain: 'listings',
    query: null,
    filters: {
      category: 'realty-flats',
    },
    preferences: {},
    location: null,
    time: null,
    sort: null,
    clarification: {
      needed: true,
      question: 'Какие параметры квартиры вас интересуют?',
      options: [],
    },
    confidence: 0.3,
    unresolved: ['квартира'],
    subqueries: [],
  },
  'Хочу что-нибудь недорогое': {
    schemaVersion: '1',
    intent: 'unknown',
    domain: null,
    query: null,
    filters: {},
    preferences: {},
    location: null,
    time: null,
    sort: null,
    clarification: {
      needed: true,
      question: 'Что именно вы ищете?',
      options: [],
    },
    confidence: 0.2,
    unresolved: ['недорого'],
    subqueries: [],
  },
  'Хочу Succeed': {
    schemaVersion: '1',
    intent: 'search',
    domain: 'listings',
    query: null,
    filters: {
      category: 'transport-cars',
      brand: 'Succeed',
    },
    preferences: {},
    location: null,
    time: null,
    sort: null,
    clarification: {
      needed: false,
      question: null,
      options: [],
    },
    confidence: 0.8,
    unresolved: [],
    subqueries: [],
  },
  'до миллиона': {
    schemaVersion: '1',
    intent: 'refine',
    domain: 'listings',
    query: null,
    filters: {
      price: {
        max: 1000000,
      },
    },
    preferences: {},
    location: null,
    time: null,
    sort: null,
    clarification: {
      needed: false,
      question: null,
      options: [],
    },
    confidence: 0.9,
    unresolved: [],
    subqueries: [],
  },
  'а автомат?': {
    schemaVersion: '1',
    intent: 'refine',
    domain: 'listings',
    query: null,
    filters: {
      gearbox: 'автомат',
    },
    preferences: {},
    location: null,
    time: null,
    sort: null,
    clarification: {
      needed: false,
      question: null,
      options: [],
    },
    confidence: 0.9,
    unresolved: [],
    subqueries: [],
  },
  'И во Владивостоке': {
    schemaVersion: '1',
    intent: 'refine',
    domain: 'listings',
    query: null,
    filters: {},
    preferences: {},
    location: {
      city: 'Владивосток',
      nearMe: false,
      preferred: false,
    },
    time: null,
    sort: null,
    clarification: {
      needed: false,
      question: null,
      options: [],
    },
    confidence: 0.9,
    unresolved: [],
    subqueries: [],
  },
};
